---
title: "Work plan"
output: html_document
---

### General idea

Main goal of the study is to apply marketing segmentation on customers of e-commerce e-commerce site. There are 2 potential profits from such analysis. First is that because of segmentation, one is able to get to know the customers better. Results of the analysis can be used for better planning of advertisement strategies. Also, one can find the most profitable products categories - this can guide future decisions about direction of further growth of the shop. 

Profits of such analysis for the business include:

- one is able to get to know the customers better
- better planning of advertising strategies - possible usage of microtargeting, optimization of expenses on campaigns because of focus on the most promising customers
- one can find the most profitable products categories - this can guide future decisions about direction of further growth of the shop
- creating recommendation system is possible - because most of the shop customers are first-timers, a problem of cold start is very important. Recommendation can be done by assigning the customer to the segment of previous customers, based on the items he already has in the cart. This is called cross-selling.
- **It is possible to create strategies for customer retention.** In the e-commerce analyzed, almost 97% of the customers never return to the site to buy again. This has a huge potential for improvement in revenue. It is usually said that it is easier to retain a customer than to obtain a new one (because of the cost). Customer segmentation offers a solution for this - explained in the next section.


The goal of the strategy  I would like to implement is to find the customers that bought in the shop only one time, and find the ones that are most likely to buy next time. After obtaining such information, it is possible to "give them a push" - for example target them with a suited advertisement, offer special discounts etc. The method is based on the fact that we have the data for the customers that bought more than one time, and we can check what are their characteristics. Specifically, this can include: price and rating of the first purchase, bought categories of products, customer location, sociodemographic variables (based on the region of the customer) - wealth, probable ethinicity, religion etc. Also, one can obtain specific information about what is the perfect time to give an advertisement for the customer - based on the time that has passed from first to second buy for previous customers. 
(The method described here is largely inspired by an analysis avaliable under this link: https://www.optimove.com/blog/how-to-convert-one-timers . 
)

The approach looks like this:

1. Split customers into 2 groups based on whether they have bought second time. 
2. Assess "loyal customers" group. Run clustering algorithm using variables present in the dataset and generated by other means (described in detail later). Use some method for assesment of variable importance to determine irrelevant variables. Important remark is that cllustering should be done for the moment **just after** the first order. This way, population of one-timers and loyal customers can be compared meaningfully. Also, PAM sounds like a good choice for the algorithm, as it gives real representation of the cluster centers.
3. Use clusters obtained on loyal customers group to "classify" customers that made just one purchase. 

It would be valuable to do all analyses in a rolling manner - to reflect the real life situation, in which data is sequentially from longer time period. This approach can also help to assess the cluster stability and how the model performs. First run of the analysis on 6-month period, then run next iteration every month. (Dataset spans almost 2 years). 

Method described above helps to get to know one-timers better. This can be used to prepare tailor-made recommendations and advertisements for them. However, an unanswered task is to judge, for which customers it is the most reasonable to spend money and effort on advertisements. It is probably the case that some customers are more likely to buy next time than the others. A challenge is to select the ones that are the most likely but still didn't do it, and focus advertising on them. To that advertising, results of clustering from the previous step can be used. 

One simple heuristic to assess attractiveness of one-timer is checking days since the first purchase. From EDA, ~60% of second orders are made in time span of 2 months after first order. Other, more sophisticated method would be to run some classification algorithm - make "if_bought_second_time" a dependent variable and check if it can be predicted. However, I have not tested such models, and I am not sure if I should extend my study for this. 

#### Potential variables to use

The dataset is very rich in variables. Some of them are ready to use as-is in clustering (like order value), but others require quite a processing (text review of the order). General topics of the variables include:

- **Order information** - order value, number of items bought, date, day of the week of the purchase, date of the delivery, delay in the delivery time, if the order was made in installments or by card (in Brazil installments payments account for majority of transactions online). This information is straightforward to obtain from the dataset. 
- **Items bought in an order** - category of the product, unit value of the product, if the price was lower than previously. This information is avaliable in the dataset. However, it is tricky to add this to main dataset, because there can be multiple items per one order. The easiest (but far from perfect) solution would be to select one category of the product to main dataset, for example category of the most costly product. However, in this way lot of information is lost. Other solution is more sophisticated, but worth trying. It involves clustering of the baskets, the details are desribed below.
- **Location info for the customer** - exact geographic location, if rural area, mean income in particular area, population density, ethnicity structure of the region. Except first one (present in the dataset), others have to be obtained from external web service (SIBRA, Brazilian statistical office). Joining of the dataset will not be straightforward. In the e-commerce dataset, assignment to particular area is done by 5-digit ZIP code. In SIBRA, resolution is avaliable to "Microregions". These two don't match at all - level of aggregation is similar, but the boundaries not. Also, specific polygons for zip codes (SHP files) are avaliable only as a paid service, and in the dataset there are only a few points present for each ZIP.
- **Review of the order** - 1-5 rating of the purchase, text review. 1-5 rating is easy to join to the main dataset, however text review is more complicated. One of the possibilities is topic modeling - as a mean to assess what the review is actually about, and what exactly did the customer rate positively/negatively. This can be done via classic Latent Dirichlet Allocation algorithm, but also newer ones that rely on word2vec idea can be used. A tricky part is that the reviews are in portuguese, but it should be quite easy to translate them via Google Translate API or other service. 

#### Market Basket Analysis - clustering of the baskets
A challenge in adding information about bought items lies in the fact that number of items is not constant for every order. Because of that, I cannot add the information to the dataset directly - adding a dummy variable column for very possible item is impossible. However, this information can be compressed using clustering. This idea is inspired by document clustering technique from text mining. In original algorithm, first frequencies of words are computed per one document. This gives a matrix where observation is a document, and variables are words. On that dataset, clustering is performed. This procedure gives a cluster assignment for every entity in the dataset, so it is possible to reduce a document into single number. 

Translation of the procedure to the basket case could be as follows. One observation is one order, and in columns there are all product categories. Weights can be a simple indicator (1 if an item of particular category was in that order), number of items from category in an order, or monetary value of all items from such order. 



### Work done so far

- Research about variable selection in clustering
- General reasearch about customer segmentation in marketing
- Analysis of the data avaliable for loyal customers (ones that bought more than one time) - in separate notebook
- Research about external datasets providers - getting to know SIBRA website. Basic dataset in good resolution is provided, including income per capita, population density and mean years of schooling.
- Basic analysis of spatial distribution of customers - in separate notebook
- First clustering with usage of Recency, Frequency, Monetary value approach - in separate notebook













