---
title: "Machine Learning for churn prediction"
author: Kamil Matuszelański
output: 
  bookdown::word_document2:
    reference_docx: resources/02_literature_review.docx
    number_sections: true
    # toc: true
    # toc_depth: 4
# output: html_document
bibliography: resources/bib.bibtex
always_allow_html: true
params:
  echo: False
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

:::{custom-style="chapters"}
chapter I
:::

# Introduction
```{r child = '01_introduction.Rmd'}
```

&nbsp;

\pagebreak

:::{custom-style="chapters"}
chapter II
:::

# Literature review
```{r child = '02_literature_review.Rmd'}
```

&nbsp;

\pagebreak

:::{custom-style="chapters"}
chapter III
:::

# Dataset description

```{r child = '03_dataset_description.Rmd'}
```

&nbsp;

\pagebreak

:::{custom-style="chapters"}
chapter IV
:::

# Methods description

```{r child = '04_methods_description.Rmd'}
```

&nbsp;

\pagebreak

:::{custom-style="chapters"}
chapter V
:::

# Results

```{r child = '05_results.Rmd'}
```

&nbsp;

\pagebreak

:::{custom-style="chapters"}
chapter VI
:::

# Summary

```{r child = '06_summary.Rmd'}
```

&nbsp;

\pagebreak

# Appendixes {-#appendixes}

```{r child = '07_appendix.Rmd'}
```

&nbsp;

\pagebreak



# References

